services:
  
  db:
    container_name: ${MYSQL_CONTAINER_NAME:-db}
    image: mysql:${MYSQL_VERSION:-latest}
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  wordpress:
    container_name: ${WORDPRESS_CONTAINER_NAME:-wordpress}
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8000:80
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
      WP_DEBUG: 1
      WP_DEBUG_LOG: 1
      WP_DEBUG_DISPLAY: 1
    volumes:
      - wp_data:/var/www/html

  wordpress-cli:
    container_name: ${CLI_CONTAINER_NAME:-cli}
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    user: '33'
    entrypoint: ["/bin/sh", "-c", "/usr/local/bin/entry-point.sh"]
    volumes:
      - wp_data:/var/www/html
      - ./woocommerce:/var/www/html/woocommerce
      - ./entry-point.sh:/usr/local/bin/entry-point.sh
    environment:
      PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_ADMIN_USER: ${WORDPRESS_ADMIN_USER}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WOOCOMMERCE_VERSION: ${WOOCOMMERCE_VERSION}
      WOOCOMMERCE_DEST: ${WOOCOMMERCE_DEST}

volumes:
  db_data:
  wp_data:


